-- require("~/.cache/wal/colors-hyprland.conf")

require("modules.monitors")
require("modules.autostart")
require("modules.env")
require("modules.plugins")
require("modules.looks")
require("modules.misc")
require("modules.input")
require("modules.keybinds")
require("modules.windowrules")
